-- supabase_schema.sql
-- SQL to create tables, enable RLS, and add public read policies.
-- Run these in the Supabase SQL editor (or with psql connected to your DB).

-- SERVICES TABLE
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- PROJECTS / GALLERY TABLE
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  description TEXT,
  image_url TEXT,
  tech TEXT[] DEFAULT ARRAY[]::text[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- CASE STUDIES TABLE
CREATE TABLE IF NOT EXISTS public.case_studies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  content TEXT,
  cover_image_url TEXT,
  tech TEXT[] DEFAULT ARRAY[]::text[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- MIGRATION: If you have an existing case_studies table without tech column, run:
-- ALTER TABLE public.case_studies ADD COLUMN IF NOT EXISTS tech TEXT[] DEFAULT ARRAY[]::text[];

-- MIGRATION: Add project link, problem, and solution fields for case studies
-- Run this if your existing table doesn't have these columns
-- ALTER TABLE public.case_studies ADD COLUMN IF NOT EXISTS project_link TEXT;
-- ALTER TABLE public.case_studies ADD COLUMN IF NOT EXISTS problem TEXT;
-- ALTER TABLE public.case_studies ADD COLUMN IF NOT EXISTS solution TEXT;

-- MIGRATION: Add avatar column for testimonials (author image)
-- Run this if your existing testimonials table doesn't have an avatar column
-- ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- TESTIMONIALS TABLE
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote TEXT NOT NULL,
  author TEXT,
  company TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- OPTIONAL: enable Row Level Security (RLS) and add a policy that allows
-- anonymous (public) SELECT for these tables so the frontend (anon key)
-- can read content. If you prefer tighter control, adjust policies accordingly.

-- Enable RLS
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_studies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- Create simple public read policies
CREATE POLICY "Public read on services" ON public.services FOR SELECT USING (true);
CREATE POLICY "Public read on projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public read on case_studies" ON public.case_studies FOR SELECT USING (true);
CREATE POLICY "Public read on testimonials" ON public.testimonials FOR SELECT USING (true);

-- Allow authenticated users to perform INSERT/UPDATE/DELETE actions.
-- These policies require the client to be authenticated (i.e. have a valid
-- session with Supabase Auth). This is the recommended approach: enable
-- public SELECT for the frontend (anon key) while restricting writes to
-- authenticated users (admins).

-- SERVICES write policies
CREATE POLICY "Authenticated insert on services" ON public.services FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update on services" ON public.services FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete on services" ON public.services FOR DELETE USING (auth.role() = 'authenticated');

-- PROJECTS / GALLERY write policies
CREATE POLICY "Authenticated insert on projects" ON public.projects FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update on projects" ON public.projects FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete on projects" ON public.projects FOR DELETE USING (auth.role() = 'authenticated');

-- CASE STUDIES write policies
CREATE POLICY "Authenticated insert on case_studies" ON public.case_studies FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update on case_studies" ON public.case_studies FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete on case_studies" ON public.case_studies FOR DELETE USING (auth.role() = 'authenticated');

-- TESTIMONIALS write policies
CREATE POLICY "Authenticated insert on testimonials" ON public.testimonials FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update on testimonials" ON public.testimonials FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete on testimonials" ON public.testimonials FOR DELETE USING (auth.role() = 'authenticated');

STORAGE: Create a public bucket for images
You can run the storage.create_bucket function in the SQL editor.
Note: The storage schema may differ between Supabase versions; the function
is commonly available as `storage.create_bucket(name, public boolean)`.
Example (creates a bucket named 'portfolio-images'):
SELECT storage.create_bucket('portfolio-images', true);

If `storage.create_bucket` is unavailable in your Supabase project,
create the bucket using the Supabase UI (Storage > Create a new bucket)
and mark it public if you want direct image reads from the browser.

STORAGE RLS POLICIES: Allow public read and authenticated write to the bucket
INSERT policy: Only authenticated users can upload
DELETE policy: Only authenticated users can delete

Enable RLS on storage.objects for 'portfolio-images' bucket
CREATE POLICY "Allow authenticated uploads to portfolio-images"
  ON storage.objects FOR INSERT WITH CHECK (
    bucket_id = 'portfolio-images' AND auth.role() = 'authenticated'
  );

CREATE POLICY "Allow public read on portfolio-images"
  ON storage.objects FOR SELECT USING (
    bucket_id = 'portfolio-images'
  );

CREATE POLICY "Allow authenticated delete from portfolio-images"
  ON storage.objects FOR DELETE USING (
    bucket_id = 'portfolio-images' AND auth.role() = 'authenticated'
  );

-- OPTIONAL: Insert sample data (uncomment to run)
-- INSERT INTO public.services (title, description, icon) VALUES
-- ('Frontend Dev', 'Building responsive interfaces with React and Tailwind.', 'layout'),
-- ('Backend Dev', 'Server-side logic and APIs with Django or Node.', 'database');

-- INSERT INTO public.projects (title, category, description, image_url, tech) VALUES
-- ('EcoTrack IoT', 'Embedded & Web', 'Real-time environmental monitoring dashboard.', 'https://images.unsplash.com/photo-...', ARRAY['React','MQTT','ESP32']),
-- ('CryptoClay UI', 'Frontend Design', 'Claymorphism-styled wallet UI.', 'https://images.unsplash.com/photo-...', ARRAY['React','CSS']);

-- INSERT INTO public.case_studies (title, description, category, content, cover_image_url, tech) VALUES
-- ('StudentHub Case Study', 'A platform for sharing student resources.', 'Fullstack', 'Full content here', 'https://images.unsplash.com/photo-...', ARRAY['Django','React']);

-- INSERT INTO public.testimonials (quote, author, company) VALUES
-- ('Great work, highly recommend!', 'Alice Wonderland', 'InnovateX');

-- Notes:
-- - If you create a public storage bucket, set object and bucket policies using
--   the Storage UI if needed. For more advanced access (uploads from clients),
--   use signed URLs or define RLS policies that check for authenticated users.
-- - For admin-only operations (insert/update/delete) from a server or CI/CD,
--   use the Supabase service role key (never expose it in client code).
